class Authrization:
    API_KEY="" #REPLACE WITH YOUR VALUES
    ADMIN_API="" #REPLACE WITH YOUR VALUES
    STORE_URL="" #REPLACE WITH YOUR VALUES
    API_VERSION="" #REPLACE WITH YOUR VALUES
    END_POINT="products.json?limit=250&since_id" 
    LAST_PRODUCT_ID="" #REPLACE WITH YOUR VALUES
    POST_URL_END_POINT="products" 
    INVENTORY_LOCATION_ID=4564561688 #REPLACE WITH YOUR VALUES
    
